### ISSUE TITLE
CL-CUDA now in Quicklisp

### ISSUE THREAD

**Issue by lukego** [melisgl/mgl#11]
The README says

> CL-CUDA and MGL-MAT are the two main dependencies and also the ones not yet in quicklisp

but CL-CUDA is in fact included in Quicklisp now (apparently since https://github.com/quicklisp/quicklisp-projects/issues/514#issuecomment-248572431).

Maybe this means that MGL-MAT and MGL could now be included in Quicklisp too...?

**Comment by melisgl** [comment]
Thanks for the heads up. MGL is now in quicklisp
