### ISSUE TITLE
Math notiation not being formatted

### ISSUE THREAD

**Issue by lukego** [melisgl/mgl#9]
The math notation doesn't seem to be formatted in the HTML documentation e.g. at https://melisgl.github.io/mgl-pax-world/mgl-manual.html#x-28MGL-GD-3A-40MGL-GD-SGD-OPTIMIZER-20MGL-PAX-3ASECTION-29.

The documentation on my machine (Chrome, Linux) looks like:

```
$$\Delta_w^{t+1} = momentum \Delta_w^t + \frac{accumulator}{batchsize} + l_2 w + l_1 sign(w)$$

$$w^{t+1} = w^{t} - learningrate \Delta_w$$

which is the same as the more traditional formulation:

$$\Delta_w^{t+1} = momentum * \Delta_w^{t} + learningrate \left(\frac{\frac{df}{dw}}{batchsize} + l_2 w + l_1 sign(w)\right)$$

$$w^{t+1} = w^{t} - \Delta_w$$```

**Comment by melisgl** [comment]
This should now be fixed by a combination of an mgl-pax (https://github.com/melisgl/mgl-pax/commit/5a973900e49878396ce901403cd8be87ad51907c) and an 3bmd workaround (e697791a9bcad3b6e7b3845246a2aa55238cfef7). Thanks for the report.
